#!/usr/bin/env python3
"""Generate assets/js/palette.js from assets/csv/color_wheel_hex.csv.

The site shows exactly three colours at any moment, all taken from ring 8.

The day is cut into 32 slots of 45 minutes. Slot i runs from (i-1)*45 minutes
after midnight to i*45 minutes, so i = minutes_since_midnight // 45 + 1.
That slot picks the three colours:

    white  -> cell (8, i)      every surface that used to be white
    black  -> cell (8, i-2)    every bar and every piece of text
    select -> cell (8, i-1)    hover / current-page states

Column indices wrap around 32, so slot 1 takes its black from column 31 and
slot 2 from column 32.

Re-run after editing the CSV:  python3 gen_palette.py
"""
import csv

CSV, OUT, RING = "assets/csv/color_wheel_hex.csv", "assets/js/palette.js", "8"
SLOTS, SLOT_MIN = 32, 45

ring = {r[0]: r[1:] for r in csv.reader(open(CSV))}[RING]
assert len(ring) == SLOTS, "ring %s has %d columns, expected %d" % (RING, len(ring), SLOTS)

def cell(k):
    """Column k, 1-indexed, wrapping around the wheel."""
    return ring[((k - 1) % SLOTS)]

table, report = [], []
for i in range(1, SLOTS + 1):
    white, black, select = cell(i), cell(i - 2), cell(i - 1)
    table.append((white, black, select))
    start, end = (i - 1) * SLOT_MIN, i * SLOT_MIN
    report.append((i, start, end, white, black, select))

rows = ",\n".join('  ["%s","%s","%s"]' % t for t in table)

open(OUT, "w").write('''/* GENERATED by gen_palette.py from assets/csv/color_wheel_hex.csv -- do not edit.

   Three colours at a time, all from ring 8 of the wheel. The day is 32 slots of
   45 minutes; slot i = minutes_since_midnight / 45 + 1, and takes

       white  = cell (8, i)        black = cell (8, i-2)
       select = cell (8, i-1)

   with the column index wrapping around 32. One row per slot, in slot order. */
(function () {
  var SLOTS = [
%s
  ];
  var SLOT_MIN = %d;

  function slotIndex(d) {
    return Math.floor((d.getHours() * 60 + d.getMinutes()) / SLOT_MIN);
  }

  function paint() {
    var now = new Date(), i = slotIndex(now), c = SLOTS[i], s = document.documentElement.style;
    s.setProperty("--white", c[0]);
    s.setProperty("--black", c[1]);
    s.setProperty("--select", c[2]);
    document.documentElement.dataset.slot = i + 1;
  }

  paint();

  // Re-paint on the next 45-minute boundary, so a page left open keeps up.
  (function schedule() {
    var now = new Date();
    var mins = now.getHours() * 60 + now.getMinutes();
    var next = (Math.floor(mins / SLOT_MIN) + 1) * SLOT_MIN;
    var ms = (next - mins) * 60000 - now.getSeconds() * 1000 - now.getMilliseconds() + 1000;
    setTimeout(function () { paint(); schedule(); }, ms);
  })();
})();
''' % (rows, SLOT_MIN))

print("wrote %s -- %d slots of %d minutes" % (OUT, SLOTS, SLOT_MIN))
print("\nslot  window       white    black    select")
for i, start, end, w, b, s in report:
    print("%4d  %02d:%02d-%02d:%02d  %s  %s  %s"
          % (i, start // 60, start % 60, (end // 60) % 24, end % 60, w, b, s))
