#!/usr/bin/env python3
r"""Sync sections of cv/cv.tex into the site's HTML pages.

Currently syncs:
    cv.tex  \begin{rSection}{Education}  ->  career.html  timeline

Both commented (% ...) and uncommented entries in the Education section are
emitted, in the order they appear in the .tex file.

Each .tex entry is a blank-line-separated block shaped like:

    {\bf PhD in Computer Science}
    \hfill \dates{August 2025 -- July 2030} \\
    The University of Texas at Dallas, Richardson, TX, USA\\
    CGPA: 3.75/4.00

which becomes a timeline tile ordered:

    line 1 of tile : institution only (3rd .tex line, address stripped)
    line 2 of tile : duration
    rest           : degree (1st .tex line), then every remaining .tex line

Usage:  python3 sync.py            # rewrite career.html in place
        python3 sync.py --check    # exit 1 if career.html is out of date
        python3 sync.py --print    # dump the generated block, touch nothing
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CV_TEX = ROOT / "cv" / "cv.tex"
CAREER_HTML = ROOT / "career.html"

# The generated region in career.html lives between these two markers.
BEGIN_MARK = "<!-- education:start -- generated by sync.py from cv/cv.tex; edit the .tex, not this -->"
END_MARK = "<!-- education:end -->"

INDENT = " " * 16  # entries sit inside <main><section><div class="timeline">

# The existing tiles render every body line in plain weight, so the {\bf ...}
# on the degree line is dropped. Flip to True to carry the bold over.
BOLD_DEGREE = False


# --------------------------------------------------------------------------
# LaTeX -> HTML
# --------------------------------------------------------------------------

def latex_to_html(s: str) -> str:
    """Convert the small subset of LaTeX used in the CV body to HTML."""
    # \href{url}{text} -> <a href="url">text</a>, stashed so escaping skips it.
    links: list[str] = []

    def stash_href(m: re.Match) -> str:
        links.append('<a href="%s">%s</a>' % (m.group(1), latex_to_html(m.group(2))))
        return "\x00%d\x00" % (len(links) - 1)

    s = re.sub(r"\\href\{([^}]*)\}\{([^}]*)\}", stash_href, s)

    # Escaped characters -> placeholders, so the HTML escape below leaves them be.
    s = s.replace(r"\&", "\x01").replace(r"\%", "%").replace(r"\_", "_")
    s = s.replace(r"\$", "$").replace(r"\#", "#")

    # Font switches. Both {\bf x} / {\em x} and \textbf{x} / \textit{x} forms.
    s = re.sub(r"\{\\(?:bf|textbf|bfseries)\s+(.*?)\}", r"<strong>\1</strong>", s)
    s = re.sub(r"\{\\(?:em|it|itshape|textit)\s+(.*?)\}", r"<em>\1</em>", s)
    s = re.sub(r"\\textbf\{(.*?)\}", r"<strong>\1</strong>", s)
    s = re.sub(r"\\(?:textit|emph)\{(.*?)\}", r"<em>\1</em>", s)
    s = re.sub(r"\\underline\{(.*?)\}", r"<u>\1</u>", s)
    s = re.sub(r"\\texttt\{(.*?)\}", r"<code>\1</code>", s)

    # Anything left with braces: drop the command, keep the argument.
    s = re.sub(r"\\[a-zA-Z]+\{(.*?)\}", r"\1", s)
    s = re.sub(r"\\[a-zA-Z]+", "", s)
    s = s.replace("{", "").replace("}", "").replace("~", " ")

    # HTML-escape what the browser would otherwise read as markup, but keep the
    # tags this function just produced.
    s = s.replace("&", "&amp;")
    s = re.sub(r"&amp;(?=(?:lt|gt|amp|mdash|ndash|nbsp|hellip);)", "&", s)
    s = s.replace("<strong>", "\x02").replace("</strong>", "\x03")
    s = s.replace("<em>", "\x04").replace("</em>", "\x05")
    s = s.replace("<u>", "\x06").replace("</u>", "\x07")
    s = s.replace("<code>", "\x0b").replace("</code>", "\x0c")
    s = s.replace("<", "&lt;").replace(">", "&gt;")
    for ph, tag in (("\x02", "<strong>"), ("\x03", "</strong>"),
                    ("\x04", "<em>"), ("\x05", "</em>"),
                    ("\x06", "<u>"), ("\x07", "</u>"),
                    ("\x0b", "<code>"), ("\x0c", "</code>")):
        s = s.replace(ph, tag)
    s = s.replace("\x01", "&amp;")

    # Dashes. Order matters: --- before --.
    s = s.replace("---", "&mdash;").replace("--", "&ndash;")

    for i, link in enumerate(links):
        s = s.replace("\x00%d\x00" % i, link)

    return re.sub(r"\s+", " ", s).strip()


# --------------------------------------------------------------------------
# cv.tex parsing
# --------------------------------------------------------------------------

def section_body(tex: str, name: str) -> str:
    """Return the raw text between \\begin{rSection}{name} and its \\end."""
    pat = re.compile(
        r"\\begin\{rSection\}\{" + re.escape(name) + r"\}(.*?)\\end\{rSection\}",
        re.DOTALL,
    )
    m = pat.search(tex)
    if not m:
        raise SystemExit("sync.py: no rSection{%s} found in %s" % (name, CV_TEX))
    return m.group(1)


def uncomment(line: str) -> str:
    """Strip a leading LaTeX comment marker so commented entries are read too."""
    stripped = line.lstrip()
    if stripped.startswith("%"):
        return stripped[1:].strip()
    return line.strip()


def entry_blocks(body: str) -> list[list[str]]:
    """Split a section body into blank-line-separated blocks of content lines."""
    blocks: list[list[str]] = []
    current: list[str] = []
    for raw in body.splitlines():
        line = uncomment(raw)
        # Formatting-only directives are not content.
        if re.fullmatch(r"\\(itemsep|vspace|smallskip|medskip|bigskip).*", line):
            line = ""
        if not line:
            if current:
                blocks.append(current)
                current = []
            continue
        current.append(line)
    if current:
        blocks.append(current)
    return blocks


class Entry:
    def __init__(self, institution: str, dates: str, lines: list[str]):
        self.institution = institution
        self.dates = dates
        self.lines = lines

    def __repr__(self) -> str:  # debugging aid
        return "Entry(%r, %r, %r)" % (self.institution, self.dates, self.lines)


def clean(line: str) -> str:
    """Drop the trailing line break and layout glue from a .tex content line."""
    line = re.sub(r"\\\\\s*$", "", line.strip())
    return line.strip()


def parse_education(tex: str) -> list[Entry]:
    entries: list[Entry] = []
    for block in entry_blocks(section_body(tex, "Education")):
        block = [clean(l) for l in block]
        block = [l for l in block if l]

        # The dates line is the one carrying \dates{...}; the institution is
        # the line right after it, and the degree is everything before it.
        idx = next((i for i, l in enumerate(block) if r"\dates{" in l), None)
        if idx is None or idx + 1 >= len(block):
            print("sync.py: skipping malformed entry: %r" % (block,), file=sys.stderr)
            continue

        dates = re.search(r"\\dates\{(.*?)\}", block[idx]).group(1)
        institution = block[idx + 1].split(",")[0]

        # Degree line(s) above the dates, then everything below the institution.
        rest = block[:idx] + block[idx + 2:]

        entries.append(Entry(
            latex_to_html(institution),
            latex_to_html(dates).replace("&ndash;", "&mdash;"),
            [latex_to_html(l) for l in rest],
        ))
    return entries


# --------------------------------------------------------------------------
# HTML generation
# --------------------------------------------------------------------------

def strip_bold(s: str) -> str:
    return s.replace("<strong>", "").replace("</strong>", "")


def render(entries: list[Entry]) -> str:
    out: list[str] = []
    for e in entries:
        out.append('%s<div class="timeline-entry">' % INDENT)
        out.append('%s    <div class="timeline-content">' % INDENT)
        out.append('%s        <h3 class="timeline-title">%s</h3>' % (INDENT, e.institution))
        out.append('%s        <p class="timeline-date">%s</p>' % (INDENT, e.dates))
        lines = e.lines if BOLD_DEGREE else [strip_bold(l) for l in e.lines]
        if lines:
            body = ("<br>\n%s" % (INDENT + " " * 11)).join(lines)
            out.append('%s        <p>%s</p>' % (INDENT, body))
        out.append('%s    </div>' % INDENT)
        out.append('%s</div>' % INDENT)
    return "\n".join(out)


def splice(html: str, block: str) -> str:
    pat = re.compile(
        r"([ \t]*)" + re.escape(BEGIN_MARK) + r".*?" + re.escape(END_MARK),
        re.DOTALL,
    )
    if not pat.search(html):
        raise SystemExit(
            "sync.py: markers not found in %s.\n"
            "Wrap the timeline entries in:\n  %s\n  ...\n  %s"
            % (CAREER_HTML, BEGIN_MARK, END_MARK)
        )
    replacement = "%s%s\n%s\n%s%s" % (INDENT, BEGIN_MARK, block, INDENT, END_MARK)
    return pat.sub(lambda _: replacement, html, count=1)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if career.html is out of date, write nothing")
    ap.add_argument("--print", dest="dump", action="store_true",
                    help="print the generated block and exit")
    args = ap.parse_args()

    entries = parse_education(CV_TEX.read_text(encoding="utf-8"))
    block = render(entries)

    if args.dump:
        print(block)
        return 0

    old = CAREER_HTML.read_text(encoding="utf-8")
    new = splice(old, block)

    if args.check:
        if old == new:
            print("sync.py: career.html is up to date (%d entries)" % len(entries))
            return 0
        print("sync.py: career.html is OUT OF DATE -- run `python3 sync.py`")
        return 1

    if old == new:
        print("sync.py: career.html already up to date (%d entries)" % len(entries))
        return 0

    CAREER_HTML.write_text(new, encoding="utf-8")
    print("sync.py: wrote %d education entries to career.html" % len(entries))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
