#!/usr/bin/env python3
r"""Sync sections of cv/cv.tex into the site's HTML pages.

Currently syncs:
    cv.tex  \begin{rSection}{Education}  ->  career.html  timeline

Both commented (% ...) and uncommented entries in the Education section are
emitted, in the order they appear in the .tex file.

Each .tex entry is a blank-line-separated block shaped like:

    {\bf PhD in Computer Science}
    \hfill \dates{August 2025 -- July 2030} \\
    The University of Texas at Dallas, Richardson, TX, USA\\
    CGPA: 3.75/4.00

which becomes a timeline tile ordered:

    line 1 of tile : institution only (3rd .tex line, address stripped)
    line 2 of tile : duration
    rest           : degree (1st .tex line), then every remaining .tex line

A line in the block that is just "lat,lon" (commented or not) is treated as the
place's location rather than body text: it is kept out of the tile and makes the
whole card a link to Google Maps with a pin dropped on that point. If an
Education entry has no such line, the place is looked up by name among the
\\begin{rSubsection}{name}{...} blocks elsewhere in the CV, so a location
recorded once (say under Research Positions) serves both. An entry with no
coordinates anywhere simply renders as a non-clickable card.

Usage:  python3 sync.py            # rewrite career.html in place
        python3 sync.py --check    # exit 1 if career.html is out of date
        python3 sync.py --print    # dump the generated block, touch nothing
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CV_TEX = ROOT / "cv" / "cv.tex"
CAREER_HTML = ROOT / "career.html"

# The generated region in career.html lives between these two markers.
BEGIN_MARK = "<!-- education:start -- generated by sync.py from cv/cv.tex; edit the .tex, not this -->"
END_MARK = "<!-- education:end -->"

INDENT = " " * 16  # entries sit inside <main><section><div class="timeline">

# The existing tiles render every body line in plain weight, so the {\bf ...}
# on the degree line is dropped. Flip to True to carry the bold over.
BOLD_DEGREE = False

# A bare "lat,lon" line inside an entry is the place's location, not body text.
# It is pulled out of the tile and turned into a Google Maps link on the card.
COORD_RE = re.compile(r"^(-?\d{1,3}(?:\.\d+)?)\s*,\s*(-?\d{1,3}(?:\.\d+)?)$")
MAPS_URL = "https://www.google.com/maps?ll=%s,%s&q=%s,%s&hl=en&t=m&z=15"


# --------------------------------------------------------------------------
# LaTeX -> HTML
# --------------------------------------------------------------------------

def latex_to_html(s: str) -> str:
    """Convert the small subset of LaTeX used in the CV body to HTML."""
    # \href{url}{text} -> <a href="url">text</a>, stashed so escaping skips it.
    links: list[str] = []

    def stash_href(m: re.Match) -> str:
        links.append('<a href="%s">%s</a>' % (m.group(1), latex_to_html(m.group(2))))
        return "\x00%d\x00" % (len(links) - 1)

    s = re.sub(r"\\href\{([^}]*)\}\{([^}]*)\}", stash_href, s)

    # Escaped characters -> placeholders, so the HTML escape below leaves them be.
    s = s.replace(r"\&", "\x01").replace(r"\%", "%").replace(r"\_", "_")
    s = s.replace(r"\$", "$").replace(r"\#", "#")

    # Font switches. Both {\bf x} / {\em x} and \textbf{x} / \textit{x} forms.
    s = re.sub(r"\{\\(?:bf|textbf|bfseries)\s+(.*?)\}", r"<strong>\1</strong>", s)
    s = re.sub(r"\{\\(?:em|it|itshape|textit)\s+(.*?)\}", r"<em>\1</em>", s)
    s = re.sub(r"\\textbf\{(.*?)\}", r"<strong>\1</strong>", s)
    s = re.sub(r"\\(?:textit|emph)\{(.*?)\}", r"<em>\1</em>", s)
    s = re.sub(r"\\underline\{(.*?)\}", r"<u>\1</u>", s)
    s = re.sub(r"\\texttt\{(.*?)\}", r"<code>\1</code>", s)

    # Anything left with braces: drop the command, keep the argument.
    s = re.sub(r"\\[a-zA-Z]+\{(.*?)\}", r"\1", s)
    s = re.sub(r"\\[a-zA-Z]+", "", s)
    s = s.replace("{", "").replace("}", "").replace("~", " ")

    # HTML-escape what the browser would otherwise read as markup, but keep the
    # tags this function just produced.
    s = s.replace("&", "&amp;")
    s = re.sub(r"&amp;(?=(?:lt|gt|amp|mdash|ndash|nbsp|hellip);)", "&", s)
    s = s.replace("<strong>", "\x02").replace("</strong>", "\x03")
    s = s.replace("<em>", "\x04").replace("</em>", "\x05")
    s = s.replace("<u>", "\x06").replace("</u>", "\x07")
    s = s.replace("<code>", "\x0b").replace("</code>", "\x0c")
    s = s.replace("<", "&lt;").replace(">", "&gt;")
    for ph, tag in (("\x02", "<strong>"), ("\x03", "</strong>"),
                    ("\x04", "<em>"), ("\x05", "</em>"),
                    ("\x06", "<u>"), ("\x07", "</u>"),
                    ("\x0b", "<code>"), ("\x0c", "</code>")):
        s = s.replace(ph, tag)
    s = s.replace("\x01", "&amp;")

    # Dashes. Order matters: --- before --.
    s = s.replace("---", "&mdash;").replace("--", "&ndash;")

    for i, link in enumerate(links):
        s = s.replace("\x00%d\x00" % i, link)

    return re.sub(r"\s+", " ", s).strip()


# --------------------------------------------------------------------------
# cv.tex parsing
# --------------------------------------------------------------------------

def section_body(tex: str, name: str) -> str:
    """Return the raw text between \\begin{rSection}{name} and its \\end."""
    pat = re.compile(
        r"\\begin\{rSection\}\{" + re.escape(name) + r"\}(.*?)\\end\{rSection\}",
        re.DOTALL,
    )
    m = pat.search(tex)
    if not m:
        raise SystemExit("sync.py: no rSection{%s} found in %s" % (name, CV_TEX))
    return m.group(1)


def uncomment(line: str) -> str:
    """Strip a leading LaTeX comment marker so commented entries are read too."""
    stripped = line.lstrip()
    if stripped.startswith("%"):
        return stripped[1:].strip()
    return line.strip()


def entry_blocks(body: str) -> list[list[str]]:
    """Split a section body into blank-line-separated blocks of content lines."""
    blocks: list[list[str]] = []
    current: list[str] = []
    for raw in body.splitlines():
        line = uncomment(raw)
        # Formatting-only directives are not content.
        if re.fullmatch(r"\\(itemsep|vspace|smallskip|medskip|bigskip).*", line):
            line = ""
        if not line:
            if current:
                blocks.append(current)
                current = []
            continue
        current.append(line)
    if current:
        blocks.append(current)
    return blocks


class Entry:
    def __init__(self, institution: str, dates: str, lines: list[str],
                 coords: tuple[str, str] | None = None):
        self.institution = institution
        self.dates = dates
        self.lines = lines
        self.coords = coords          # (lat, lon) as written, or None

    @property
    def map_url(self) -> str | None:
        if not self.coords:
            return None
        lat, lon = self.coords
        return MAPS_URL % (lat, lon, lat, lon)

    def __repr__(self) -> str:  # debugging aid
        return "Entry(%r, %r, %r, %r)" % (self.institution, self.dates,
                                          self.lines, self.coords)


def clean(line: str) -> str:
    """Drop the trailing line break and layout glue from a .tex content line."""
    line = re.sub(r"\\\\\s*$", "", line.strip())
    return line.strip()


def norm(name: str) -> str:
    """Key for matching a place across sections: case- and space-insensitive."""
    return re.sub(r"\s+", " ", name).strip().lower()


def subsection_coords(tex: str) -> dict[str, tuple[str, str]]:
    """Map place name -> coordinates for every \\begin{rSubsection}{name}{...}
    block in the file that carries a "lat,lon" line.

    Education entries are the primary source, but a place may only have its
    coordinates recorded elsewhere -- Inverse AI, for instance, is listed under
    Research Positions. This is the fallback those entries use.
    """
    found: dict[str, tuple[str, str]] = {}
    pat = re.compile(r"\\begin\{rSubsection\}\{(.*?)\}\{.*?\}(.*?)\\end\{rSubsection\}",
                     re.DOTALL)
    for m in pat.finditer(tex):
        name, body = m.group(1), m.group(2)
        for raw in body.splitlines():
            hit = COORD_RE.match(uncomment(raw))
            if hit:
                lat, lon = hit.group(1), hit.group(2)
                if -90 <= float(lat) <= 90 and -180 <= float(lon) <= 180:
                    found.setdefault(norm(latex_to_html(name)), (lat, lon))
                break
    return found


def parse_education(tex: str) -> list[Entry]:
    elsewhere = subsection_coords(tex)
    entries: list[Entry] = []
    for block in entry_blocks(section_body(tex, "Education")):
        block = [clean(l) for l in block]
        block = [l for l in block if l]

        # The dates line is the one carrying \dates{...}; the institution is
        # the line right after it, and the degree is everything before it.
        idx = next((i for i, l in enumerate(block) if r"\dates{" in l), None)
        if idx is None or idx + 1 >= len(block):
            print("sync.py: skipping malformed entry: %r" % (block,), file=sys.stderr)
            continue

        dates = re.search(r"\\dates\{(.*?)\}", block[idx]).group(1)
        institution = block[idx + 1].split(",")[0]

        # Degree line(s) above the dates, then everything below the institution.
        rest = block[:idx] + block[idx + 2:]

        # A bare "lat,lon" line is location data, so lift it out of the body.
        coords = None
        body: list[str] = []
        for line in rest:
            m = COORD_RE.match(line)
            if m and coords is None:
                lat, lon = m.group(1), m.group(2)
                if not (-90 <= float(lat) <= 90 and -180 <= float(lon) <= 180):
                    print("sync.py: %s has out-of-range coordinates %s,%s"
                          % (institution, lat, lon), file=sys.stderr)
                else:
                    coords = (lat, lon)
                continue
            body.append(line)

        # Not stated in Education? Look for the place elsewhere in the CV.
        if coords is None:
            coords = elsewhere.get(norm(institution))

        if coords is None:
            print("sync.py: no coordinates for %s; its card will not link"
                  % institution, file=sys.stderr)

        entries.append(Entry(
            latex_to_html(institution),
            latex_to_html(dates).replace("&ndash;", "&mdash;"),
            [latex_to_html(l) for l in body],
            coords,
        ))
    return entries


# --------------------------------------------------------------------------
# HTML generation
# --------------------------------------------------------------------------

def strip_bold(s: str) -> str:
    return s.replace("<strong>", "").replace("</strong>", "")


def render(entries: list[Entry]) -> str:
    """Emit the entries as two independent columns.

    Each column is its own flow, so cards on the same side of the stem stack
    flush instead of reserving a row for the card opposite them. Entries
    alternate between the columns, and the FIRST column is the one drawn on the
    right (career.html lays the pair out with flex-direction: row-reverse), so
    the newest entry stays first in the source.

    Each entry also carries its chronological position as --i, which the mobile
    breakpoint uses to re-interleave the two columns back into one ordered run.
    """
    columns: list[list[tuple[int, Entry]]] = [[], []]
    for idx, e in enumerate(entries):
        columns[idx % 2].append((idx + 1, e))

    out: list[str] = []
    for column in columns:
        out.append('%s<div class="timeline-col">' % INDENT)
        for order, e in column:
            out.append('%s    <div class="timeline-entry" style="--i: %d">' % (INDENT, order))
            url = e.map_url
            if url:
                out.append('%s        <a class="timeline-content" href="%s" '
                           'target="_blank" rel="noopener">'
                           % (INDENT, url.replace("&", "&amp;")))
            else:
                out.append('%s        <div class="timeline-content">' % INDENT)
            out.append('%s            <h3 class="timeline-title">%s</h3>' % (INDENT, e.institution))
            out.append('%s            <p class="timeline-date">%s</p>' % (INDENT, e.dates))
            lines = e.lines if BOLD_DEGREE else [strip_bold(l) for l in e.lines]
            if lines:
                body = ("<br>\n%s" % (INDENT + " " * 15)).join(lines)
                out.append('%s            <p>%s</p>' % (INDENT, body))
            out.append('%s        </%s>' % (INDENT, "a" if url else "div"))
            out.append('%s    </div>' % INDENT)
        out.append('%s</div>' % INDENT)
    return "\n".join(out)


def splice(html: str, block: str) -> str:
    pat = re.compile(
        r"([ \t]*)" + re.escape(BEGIN_MARK) + r".*?" + re.escape(END_MARK),
        re.DOTALL,
    )
    if not pat.search(html):
        raise SystemExit(
            "sync.py: markers not found in %s.\n"
            "Wrap the timeline entries in:\n  %s\n  ...\n  %s"
            % (CAREER_HTML, BEGIN_MARK, END_MARK)
        )
    replacement = "%s%s\n%s\n%s%s" % (INDENT, BEGIN_MARK, block, INDENT, END_MARK)
    return pat.sub(lambda _: replacement, html, count=1)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if career.html is out of date, write nothing")
    ap.add_argument("--print", dest="dump", action="store_true",
                    help="print the generated block and exit")
    args = ap.parse_args()

    entries = parse_education(CV_TEX.read_text(encoding="utf-8"))
    block = render(entries)

    if args.dump:
        print(block)
        return 0

    old = CAREER_HTML.read_text(encoding="utf-8")
    new = splice(old, block)

    if args.check:
        if old == new:
            print("sync.py: career.html is up to date (%d entries)" % len(entries))
            return 0
        print("sync.py: career.html is OUT OF DATE -- run `python3 sync.py`")
        return 1

    if old == new:
        print("sync.py: career.html already up to date (%d entries)" % len(entries))
        return 0

    CAREER_HTML.write_text(new, encoding="utf-8")
    print("sync.py: wrote %d education entries to career.html" % len(entries))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
